config/routes.rb
Rails.application.routes.draw do  
  devise_for :admins, controllers: {sessions: 'admins/sessions'}
  devise_for :users, controllers: {sessions: 'users/sessions'}
  get '/posts_create', to:'posts#create'
  resources :posts do
  resources :comments
  end

  root 'posts#index'
  get '/lazalde', to: 'posts#new'
  get '/christian',to: 'post#index'
  









end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates_presence_of :title, :message=>"El campo esta vacio"
    validates_length_of :body, :in=> 10..400,:message=>"longitud no valida"
    belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  protect_from_forgery :except => [:index, :create, :new]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json

  def index
    if admin_signed_in?
      authenticate_admin!
      @posts = Post.all
        respond_to do |format|
          format.json do
            render :json => @posts, :callback => params[:callback]
          end
        format.html
      end
    else
      authenticate_user!
      @posts = current_user.posts
    end
  end  
  # GET /posts/1
  # GET /posts/1.json

  def show
    @posts = Post.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if admin_signed_in?
      if cannot? :edit, @post
        flash[:alert]= "No tienes permisos para editar el post"
        redirect_to :action => 'index', :format=>'html'
      end
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = 1

    respond_to do |format|
      if @post.save
        flash[:success]="Guardado correctamente"
        format.html{redirect_to @post}
        #format.html { redirect_to @post, notice: 'Post was successfully created.' }
        #format.json { render :show, status: :created, location: @post }
        format.json do
          render :json=>@post, :callback=> params[:callbak]
        end
      else
        format.html { render :new }
        flash[:alert]="No se pudo guardar"        
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        flash[:success]="Se actualizo correctamente"
        format.html{redirect_to @post}
        format.json { render :show, status: :ok, location: @post }
      else
        format.html{render :edit}
        flash[:alert]="Imposible actualizar"        
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      flash[:alert]="Eliminado correctamente"
      format.html{redirect_to posts_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => 'validate[required,minSize[8]]' %>
  </div>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :class => 'validate[required,minSize[10]]' %>
  </div>  

   <section class="row">
    <div class="small-4 columns">
      <div class="actions">
        <%= f.submit 'Aceptar', :class => 'button round btn' %>
      </div>    
    </div>
  </section>
<% end %>


app/views/posts/_navigationbar.html.erb
<nav class="top-bar" style="background-color: #0092B2;" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
    <h1><%= link_to 'POST',controller: '/posts', action: 'index'%></h1>
  </li>
  </ul>

  <section class="top-bar-section">
    <ul class="left">
      <li class="has-dropdown not-click"><a href="#">Menu</a>
        <ul class="dropdown">
        <li class="parent-link show-for-small-only"<a parent-link js-generated href="">Inicio</a></li>
        <li><label>Post</label></li>
        <% if admin_signed_in?%>
          <li><%= link_to'List',controller:'/posts',action:'index'%></li>
        <% else %>
          <li><%= link_to'List',controller:'/posts',action:'index'%></li>
          <li><%= link_to'New',controller:'/posts',action:'new'%></li>
        <%end%>
        <!--<li><label>Back</label></li>
        <li><label><%=link_to 'Back', posts_path %></label></li>-->    
      </ul>
      </li>
      <li class="divider"></li>
    </ul>


    <!-- Right Nav Section -->
    <ul class="navbar-text pull-right right">

    <% if user_signed_in?%>
      <li><a>Logged ini as <strong id= "login"><%=current_user.email%></strong>.</a></li>
      <li class="divider"></li>
      <li class="has-dropdown not-click"><a href="">User</a>
        <ul class="dropdown">
          <li class="parent-link show-for-small-only"<a parent-link js-generated href="">Start</a></li>
          <li><label>Post</label></li>
          <li><%=link_to 'Edit Profile', edit_user_registration_path, :class=>'navbar-link'%></li>
          <li><%=link_to "Logout", destroy_user_session_path, method: :delete, :class=>'navbar-link'%></li>
        </ul>
      </li>        
    <% end %>


    <% if admin_signed_in?%>
      <li><a>Logged ini as <strong id= "login"><%=current_admin.email%></strong>.</a></li>
      <li class="divider"></li>
      <li class="has-dropdown not-click"><a href="">Admin</a>
        <ul class="dropdown">
          <li class="parent-link show-for-small-only"<a parent-link js-generated href="">Start</a></li>
          <li><label>Post</label></li>
          <li><%=link_to 'Edit Profile', edit_admin_registration_path, :class=>'navbar-link'%></li>
          <li><%=link_to "Logout", destroy_admin_session_path, method: :delete, :class=>'navbar-link'%></li>
        </ul>
      </li>        
    <% end %>


      <% if !admin_signed_in? && !user_signed_in?  %> 
      <li><a><%=link_to "Sign up", new_user_registration_path,:class=>'navbar-link'%></a></li>
      <li><%=link_to "Login", new_user_session_path,:class=>'navbar-link'%></li>
      <!--<li><%= link_to "Login Admin", new_admin_session_path, :class => 'navbar-link' %></li> -->
      <% end %> 
      
    </ul>
  </section>
</nav>

app/views/posts/edit.html.erb
<section class="margins">
	<h1>Editing Post</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @post %> |
	<%= link_to 'Back', posts_path %>
</section>

app/views/posts/index.html.erb
<section class="margins">
  <h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <% if admin_signed_in? %>
        <th>email</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>
        <td><%= User.find(post.user_id).email%></td>
        <td>
          <%if post.body %>
            <a href="#" data-reveal-id="post-<%=post.id%>">Show more</a>
              <div id="post-<%=post.id%>" class="reveal-modal" data-reveal>
                <%=post.body%>
                <a class="close-reveal-modal">&#215;</a>          
            </div>
          <%end%>
       </td>
        <!--<% if admin_signed_in? %>
        <td><%= User.find(post.user_id).email%></td>
        <%end%>
        <!--<td><%= link_to 'Show', post %></td>-->
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  <% if !admin_signed_in? %>
    <%= link_to 'New Post', new_post_path, :class => 'button round btn' %>
  <% end %>
</section>

app/views/posts/new.html.erb
<section class="margins">
	<h1>New Post</h1>

	<%= render 'form' %>

	<%= link_to 'Back', posts_path %>
</section>

app/views/posts/show.html.erb
<section class="margins">
  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @post.body %>
  </p>

  <div id="comments">
    <%=render :partial => @post.comments.reverse %>
  </div>

  <%= form_for([@post, Comment.new], remote: true) do |f|%>
    <p><%=f.label :body, "New Comment" %><br>
      <%= f.text_area :body, :class => 'validate[required,minSize[20]]' %>
    </p>
    <p>
      <%= f.submit "Add Comment", :class => 'button round btn' %>
    </p>
  <% end %>

  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
</section>